### ISSUE TITLE
Thinking about CMB lensing constraints

### ISSUE THREAD

**Issue by drphilmarshall** [rogerblandford/Music#12]
@kstory8 and I were just discussing this CMB lensing projected potential map, from [Planck 2015 Paper XV](http://arxiv.org/pdf/1502.01591v1.pdf):

![image](https://cloud.githubusercontent.com/assets/710903/9826382/9e3f2034-588e-11e5-8e5c-4a85bad735cc.png)

Look how much power there is at l's of a few tens - not much smaller than what we are currently considering:

![image](https://cloud.githubusercontent.com/assets/710903/9826576/3fcf059e-5890-11e5-98fd-242f3d69a401.png)

Let's think a bit about how to incorporate the weak lensing effect into our model! 

@kstory8 the current version of our paper is in the doc directory, [here](https://github.com/rogerblandford/Music/raw/master/doc/music.pdf) - you can see our current, very simple, model, and its nicely linear response function. I guess including the lensing effect of the potential inside the sphere at redshifts/epochs 0 < z < 1000 on the temperature and polarisation of the gas at z=1000 will make our model interestingly non-linear, so it could be fun to start thinking through how to handle that likelihood function.

**Comment by drphilmarshall** [comment]
PS. @kstory8 is, of course, new KIPAC fellow Kyle Story :-)

**Comment by kstory8** [comment]
Hi all,
I'll skim the current version of the paper this weekend.  Intuitively, I don't expect evolving the potential at the last scattering surface to produce much of a constraint on the integrated gravitational lensing potential (I could be wrong though!), but it does sound promising to go the other way, specifically, take the integrated lensing potential map from Planck and use it to help constrain the potential at the surface of last scattering.  We have phase-full information in the Planck lensing map.  Thus in principle we could take a 3D lensing potential calculated from the LSS and integrate it, accounting for the evolution in time, using the standard Equation 1 from  Planck 2015 Paper XV, the compare the results to the lensing map?  Not sure how you would do this in practice, but the idea doesn't sound completely crazy!

**Comment by rogerblandford** [comment]
Hi,
Good to hear from you.
Hope the job is going well.
And for Sam.
Glad you have a few cycles left for the universe.
Just to clarify, the sequence that we are following is first to try to extract the very lowest Fourier components - only a few but critical - using the recombination surface alone. This appears to be possible with simulations but what happens with real data depends upon the accuracy and internal consistency of the measurements and covariance matrix. As of this writing, I believe Phil and I are now speaking a common language but my first quick effort to implement this last week produced nonsense. I will have time to repeat this more systematically later this week and we will keep you posted. Once this is done it will provide a foundation for adding the interior volumetric information including CMB lensing and yes we do intend to evolve the potentials, which change relatively little, with time. This should extend the Fourier spectrum to shorter wavelength and may even improve the accuracy of the longest wavelength modes. If the surface information turns out to be useless for this purpose, then I, for one, will have to rethink but I still believe it should work.
Best,
Roger
On Sep 11, 2015, at 6:47 PM, Kyle Story <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi all,
I'll skim the current version of the paper this weekend. Intuitively, I don't expect evolving the potential at the last scattering surface to produce much of a constraint on the integrated gravitational lensing potential (I could be wrong though!), but it does sound promising to go the other way, specifically, take the integrated lensing potential map from Planck and use it to help constrain the potential at the surface of last scattering. We have phase-full information in the Planck lensing map. Thus in principle we could take a 3D lensing potential calculated from the LSS and integrate it, accounting for the evolution in time, using the standard Equation 1 from Planck 2015 Paper XV, the compare the results to the lensing map? Not sure how you would do this in practice, but the idea doesn't sound completely crazy!
