### ISSUE TITLE
Commander tarball has two copies of *00051.fits, in each of apparently four "sets" of posterior samples

### ISSUE THREAD

**Issue by drphilmarshall** [rogerblandford/Music#14]
Hi @HKE

It took us a while to notice it but in the tarball of Commander maps that you prepared for us, the `*k00051.fits` files each appear twice, with the same file name but different time stamp:

![image](https://cloud.githubusercontent.com/assets/710903/10051141/e68b368a-61d4-11e5-965e-83a3a7e9f298.png)

We are ignoring the first of these for now, and just working with the 96 uniquely named files. Is this correct? I wondered if the 00051 maps are Metropolis samples where the proposal was not accepted - in which case we _should_ be using 00051 twice. 

This also made us wonder: why is it the 00051 is repeated in each of the four sets of samples (`c0000`, `c0001`, `c0002`, and `c0003`)? Are we correct to presume that each FITS file is a faithful sample from the posterior PDF for temperature maps, or is there some other way to interpret the four sets of samples?  

Thanks!

Phil

**Comment by hke** [comment]
Hi Phil,

> It took us a while to notice it but in the tarball of Commander maps
> that you prepared for us, the |*k00051.fits| files each appear twice,
> with the same file name but different time stamp:
> 
> image
> https://cloud.githubusercontent.com/assets/710903/10051141/e68b368a-61d4-11e5-965e-83a3a7e9f298.png
> 
> We are ignoring the first of these for now, and just working with the 96
> uniquely named files. Is this correct? I wondered if the 00051 maps are
> Metropolis samples where the proposal was not accepted - in which case
> we /should/ be using 00051 twice.
> 
> This also made us wonder: why is it the 00051 is repeated in each of the
> four sets of samples (|c0000|, |c0001|, |c0002|, and |c0003|)? Are we
> correct to presume that each FITS file is a faithful sample from the
> posterior PDF for temperature maps, or is there some other way to
> interpret the four sets of samples?

First, c indicates 'chain', and so Ingunn apparently ran with four 
independent chains when producing these samples. They are all drawn from 
the same posterior, yes, so you can use all of them interchangeably.

As for the 51st sample, I don't even see how that's possible, I have to 
admit -- there should be only one file with a given filename inside the 
tarball. Furthermore, to me it seems like the two copies have identical 
time stamps (1:09 PM). On the other hand, sample 52 is missing, which is 
odd. This looks like a file system bug of some sort to me. Ingunn -- can 
you please untar the file on your side, and check if you see something 
similar?

In any case, you can just remove any weird files, yes -- they should all 
correspond to the same posterior.

Thanks,

Hans Kristian

**Comment by drphilmarshall** [comment]
Excellent, thanks @HKE! We'll proceed with 96 samples.

As you might have guessed, we are currently rate-limited by mundane but
vital matrix indexing/book-keeping set-up, but hope to have some 3D
potential maps to show soon. Early indications suggest that, as expected,
we'll need to use (and interpret) pseudo-inverses, but we are hopeful of
being able to make sensible maps nonetheless :-)

**Comment by hke** [comment]
Hi all,

Due to a typo I did indeed pack samples 51 twice, and never packed samples 52. It is fine running with the 96 you already have, but in case you want all 100, I have replaced the tarball:

http://folk.uio.no/ingunnkw/planck/32band/commander_32band_Clsamples100.tar.gz

(It was new to me that if you add the same file twice to a tarball it can be unpacked as two different files with the same  file name and different time stamps. I don't see that on my end since they overwrite each other after unpacking.)

Thanks,

Ingunn

**Comment by drphilmarshall** [comment]
Thanks Ingunn! Do you have a GitHub account? If you "watch" the Music repo
you'll get all our emails automatically (and will be able to reply directly
and world-visibly too). Send me an email offline if you need help getting
set up, I'd be happy to help!

**Comment by ingunnkw** [comment]
I have a github account (ingunnkw) and I do follow rogerblandford/Music and I do get Music e-mails, but I haven't used git for anything but uploading and downloading code and it seems obvious that I don't know how the message system works. When I reply to an e-mail (from my normal e-mail browser) my e-mails appear as if sent by someone else. I just updated my github e-mail address to exactly match my default sender address (instead of the alias that previously was default), so I am testing whether that helped. Sorry for the spam!

Ingunn

**Comment by ingunnkw** [comment]
ok, that worked, will stop spamming you now

**Comment by drphilmarshall** [comment]
That worked great! Glad to be in touch with you, Ingunn :-) Thanks for all
your help!
